[build-system]
build-backend = "maturin"
requires = ["maturin>=1"]

[project]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: File Formats :: JSON",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only"
]
dependencies = ["bitarray", "cbor2", "msgpack>=1", "universal_pathlib"]
description = "binary json representation (msgpack or cbor) with lazy/partial loading containers"
keywords = ["msgpack", "cbor", "serialization", "lazy loading"]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
name = "msglc"
readme = "README.md"
requires-python = ">=3.10"
version = "000000"

[[project.authors]]
name = "Theodore Chang"
email = "tlcfem@gmail.com"

[[project.maintainers]]
name = "Theodore Chang"
email = "tlcfem@gmail.com"

[project.optional-dependencies]
all = ["msglc[dev]", "numpy", "msgspec", "ormsgpack", "s3fs"]
dev = [
    "zensical",
    "mkdocstrings[python]",
    "pytest-asyncio",
    "pytest-benchmark",
    "pytest-cov",
    "ruff"
]
msgspec = ["msgspec"]
numpy = ["numpy"]
ormsgpack = ["ormsgpack"]
s3fs = ["s3fs"]

[project.urls]
"Bug Reports" = "https://github.com/TLCFEM/msglc/issuess"
Homepage = "https://github.com/TLCFEM/msglc"
Source = "https://github.com/TLCFEM/msglc"

[tool.maturin]
exclude = [
    ".github/**/*",
    ".gitignore",
    "docs/**/*",
    "scripts/**/*",
    "tests/**/*",
    "zensical.toml"
]
module-name = "msglc.msglc_rust"
python-source = "src"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "strict"
tmp_path_retention_policy = "none"

[tool.ruff.lint]
ignore = ["B008", "E501"]
select = ["E", "F", "UP", "B", "SIM", "I"]
