services:
  rustfs:
    image: rustfs/rustfs:latest
    restart: no
    container_name: rustfs
    environment:
      RUSTFS_ACCESS_KEY: msglcadmin
      RUSTFS_SECRET_KEY: msglcadmin
    ports:
      - "9000:9000"
      - "9001:9001"
  seaweedfs:
    image: chrislusf/seaweedfs
    restart: no
    container_name: seaweedfs
    environment:
      AWS_ACCESS_KEY_ID: msglcadmin
      AWS_SECRET_ACCESS_KEY: msglcadmin
    ports:
      - "8333:8333"
