name: Benchmark
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Clone
        uses: actions/checkout@v6
      - name: Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.11
      - name: Test
        run: |
          uv venv
          uv pip install ".[all]" matplotlib h5py psutil
          uv run python3 ./tests/h5/generate.py
          uv run python3 ./tests/h5/read.py
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: msglc-benchmark
          path: .dirty/*.pdf
          include-hidden-files: true
