concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  benchmark:
    name: Benchmark
    runs-on: ${{ matrix.os }}
    services:
      rustfs:
        env:
          RUSTFS_ACCESS_KEY: msglcadmin
          RUSTFS_SECRET_KEY: msglcadmin
        image: rustfs/rustfs:latest
        ports:
          - '9000:9000'
      seaweedfs:
        env:
          AWS_ACCESS_KEY_ID: msglcadmin
          AWS_SECRET_ACCESS_KEY: msglcadmin
        image: chrislusf/seaweedfs
        ports:
          - '8333:8333'
    steps:
      - name: Clone
        uses: actions/checkout@v7
      - name: Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build
        run: |
          uv venv
          uv pip install ".[all]"
          uv run pytest tests/
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    timeout-minutes: 60
  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, '[publish]')
    needs:
      - benchmark
      - test
    secrets: inherit
    uses: ./.github/workflows/publish.yml
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      rustfs:
        env:
          RUSTFS_ACCESS_KEY: msglcadmin
          RUSTFS_SECRET_KEY: msglcadmin
        image: rustfs/rustfs:latest
        ports:
          - '9000:9000'
      seaweedfs:
        env:
          AWS_ACCESS_KEY_ID: msglcadmin
          AWS_SECRET_ACCESS_KEY: msglcadmin
        image: chrislusf/seaweedfs
        ports:
          - '8333:8333'
    steps:
      - name: Clone
        uses: actions/checkout@v7
      - name: Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: llvm-tools
      - name: Coverage
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build
        run: |
          uv venv
          source <(cargo llvm-cov show-env --sh)
          export CARGO_TARGET_DIR=$CARGO_LLVM_COV_TARGET_DIR
          uv pip install -e ".[all]" maturin
          uv run maturin develop --uv
          uv run ruff check --statistics .
          uv run pytest --cov=msglc --cov-report=xml tests/
          cargo llvm-cov report --lcov --output-path coverage.lcov
      - name: Upload
        uses: codecov/codecov-action@v7
        with:
          files: coverage.lcov,coverage.xml
          plugins: pycoverage,gcov
          token: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      matrix:
        python-version:
          - '3.14'
    timeout-minutes: 60
name: CICD
'on':
  pull_request: null
  push: null
