name: Wheels
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  wheels:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: pipx run build --sdist
      - name: Check
        run: pipx run twine check dist/*
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: contains(github.event.head_commit.message, '[publish]')
        with:
          user: __token__
          password: ${{ secrets.PYPI }}
      - uses: actions/upload-artifact@v4
        with:
          name: msglc-sdist
          path: dist/*.tar.gz
